In [ ]:
 import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_csv("/wk8-customers.csv")
df.head(5)

,customer_id,first_name,last_name,email,phone,address,city,state,zip_code,registration_date
0,1,James,Smith,james.smith@gmail.com,555-123-4567,123 Main St,New York,NY,10001,2021-03-15
1,2,Mary,Johnson,NaN,212.555.6789,456 Park Ave,New York,NY,10022,2020-11-02
2,3,John,Williams,jwilliams@yahoo.com,(555) 987-6543,789 Broadway,Los Angeles,California,90001-1234,2021-05-20
3,4,Patricia,Brown,pbrown@hotmail.com,5551234567,321 Elm St,Chicago,IL,60601,NaN
4,5,Robert,Jones,rjones23@gmail.com,555-987-3456,555 Pine St,Houston,TX,77002,2020-09-12

In [ ]:
df = pd.read_csv("/wk8-customers.csv")
df["registration_date"] = df["registration_date"].ffill()

In [ ]:
df.isna().sum().sum()

np.int64(9)

In [ ]:
df = pd.read_csv("/wk8-customers.csv")
df["state"].value_counts()

state
TX                4
CA                3
NY                2
IL                1
California        1
AZ                1
PA                1
Texas             1
FL                1
OH                1
North Carolina    1
IN                1
Washington        1
CO                1
MA                1
Oregon            1
NV                1
MI                1
TN                1
Maryland          1
MD                1
KY                1
WI                1
NM                1
MO                1
Name: count, dtype: int64

In [ ]:
df = pd.read_csv("/wk8-inventory.csv")
df.head(5)

,inventory_id,store_id,product_id,quantity_in_stock,last_restock_date,reorder_level
0,1,1,1,25,2022-10-15,10.0
1,2,1,5,42,2022-11-02,15.0
2,3,1,10,18,2022-09-30,8.0
3,4,1,15,5,2022-10-20,10.0
4,5,1,20,12,NaN,15.0

In [ ]:
df = pd.read_csv("/wk8-inventory.csv")
df.fillna(df.mean(numeric_only=True), inplace=True)

In [ ]:
df = pd.read_csv("/wk8-inventory.csv")
total = df["quantity_in_stock"].sum()
print(total)

1698

In [ ]:
df = pd.read_csv("/wk8-products.csv")
df.head(5)

,product_id,product_name,category,subcategory,brand,price,cost,weight
0,1,Apple iPhone 13,Electronics,Smartphones,Apple,899.99,649.99,0.45
1,2,Samsung Galaxy S21,electronics,Smartphones,Samsung,799.99,539.99,0.50
2,3,Sony WH-1000XM4,ELECTRONICS,Headphones,Sony,349.99,210.00,0.60
3,4,Dell XPS 13,Electronics,Laptops,Dell,1299.99,899.99,2.80
4,5,Nike Classic Tee,Clothing,Shirts,Nike,24.99,12.50,0.20

In [ ]:
df = pd.read_csv("/wk8-products.csv")
df.nlargest(5, "price")

,product_id,product_name,category,subcategory,brand,price,cost,weight
3,4,Dell XPS 13,Electronics,Laptops,Dell,1299.99,899.99,2.80
0,1,Apple iPhone 13,Electronics,Smartphones,Apple,899.99,649.99,0.45
1,2,Samsung Galaxy S21,electronics,Smartphones,Samsung,799.99,539.99,0.50
19,20,Dyson V11 Vacuum,HOME & KITCHEN,Appliances,Dyson,599.99,375.00,6.70
26,27,Sony PlayStation 5,Electronics,Gaming,Sony,499.99,399.00,4.50

In [ ]:
df = pd.read_csv("/wk8-products.csv")
df["product_name"].nunique()

30

In [ ]:
df = pd.read_csv("/wk8-products.csv")
total = df["price"].sum()
print(total)

5751.719999999999

In [ ]:
# Check for and remove duplicate entries in the products dataframe
products_df = pd.read_csv("/wk8-products.csv")
initial_products_rows = len(products_df)
print(f"Initial number of rows in products dataframe: {initial_products_rows}")
products_duplicates_found = products_df.duplicated().sum()
if products_duplicates_found > 0:
    products_df.drop_duplicates(inplace=True)
    print(f"Number of duplicate rows removed from products dataframe: {products_duplicates_found}")
    print(f"New number of rows in products dataframe: {len(products_df)}")
else:
    print("No duplicate rows found in products dataframe.")

print("-" * 30)

# Check for and remove duplicate entries in the customers dataframe
customers_df = pd.read_csv("/wk8-customers.csv")
initial_customers_rows = len(customers_df)
print(f"Initial number of rows in customers dataframe: {initial_customers_rows}")
customers_duplicates_found = customers_df.duplicated().sum()
if customers_duplicates_found > 0:
    customers_df.drop_duplicates(inplace=True)
    print(f"Number of duplicate rows removed from customers dataframe: {customers_duplicates_found}")
    print(f"New number of rows in customers dataframe: {len(customers_df)}")
else:
    print("No duplicate rows found in customers dataframe.")

Initial number of rows in products dataframe: 30
No duplicate rows found in products dataframe.
------------------------------
Initial number of rows in customers dataframe: 31
No duplicate rows found in customers dataframe.

In [ ]:
df = pd.read_csv("/wk8-sales.csv")
df.head(5)

,sale_id,date,store_id,customer_id,product_id,quantity,total,payment_method
0,1,2022-01-15,3.0,12,5,2,49.98,Credit Card
1,2,2022-01-16,1.0,5,10,1,49.99,credit card
2,3,2022-01-18,2.0,8,3,1,349.99,DEBIT CARD
3,4,2022-01-20,4.0,20,7,1,349.99,Cash
4,5,2022-01-22,5.0,3,15,1,1599.99,CC

In [ ]:
df = pd.read_csv("/wk8-sales.csv")
df["date"] = df["date"].ffill()

In [ ]:
df = pd.read_csv("/wk8-sales.csv")
total = df["total"].sum()
print(total)

14091.86

In [ ]:
df = pd.read_csv("/wk8-stores.csv")
df.head(5)

,store_id,store_name,address,city,state,zip_code,region,size_sqft,opening_date
0,1,City Center,123 Retail Blvd,New York,NY,10001,Northeast,32500.0,2005-05-20
1,2,Mall of Chicago,456 Shopping Ave,Chicago,IL,60611,Midwest,45000.0,2007-08-15
2,3,Los Angeles Plaza,789 Commerce St,Los Angeles,CA,90001,West,55000.0,2004-03-10
3,4,Houston Galleria,321 Main St,Houston,Texas,77002,Southwest,NaN,2008-11-05
4,5,Phoenix Outlet,654 Desert Rd,Phoenix,AZ,85001,Southwest,18500.0,2010-06-30

In [ ]:
## Replace with the column mean
df = pd.read_csv("/wk8-stores.csv")
df["size_sqft"].mean()

np.float64(30653.846153846152)

In [ ]:
df = pd.read_csv("/wk8-stores.csv")
df.loc[df["size_sqft"].idxmax()]

store_id                        3
store_name      Los Angeles Plaza
address           789 Commerce St
city                  Los Angeles
state                          CA
zip_code                    90001
region                       West
size_sqft                 55000.0
opening_date           2004-03-10
Name: 2, dtype: object

1. What are the key advantages of using Pandas for data cleaning compared to other methods?
*I appreciate Panda, because it seems easier to learn and to navigate information without acutally having to know what's going on.  You simply need to know the functions.*

2. How would your approach to handling missing values differ if the missing data was not random but had a pattern or meaning?
I would average the data and place the average number in the missing value.

3. What types of data quality issues might not be immediately visible through simple DataFrame inspection methods? The missing dates or cost of products, things of that nature will be immediately visible and can become an extreme issue in finding valuable information.

4. How would you document your data cleaning process to ensure reproducibility?  I would use the ## method and keep notes as it is human readable and not seen from the cpu.

5. In what scenarios might it be better to remove rows with missing values rather than imputing them? Im puting rows can adjust the numbers on the columns which tampers with the true results of your data.  You can report numbers that are inaccurate.